version: '3.8'

services:
  web:
    build: .
    container_name: company-car-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://admin:123456@postgres:5432/car_system?schema=public
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm start"

  postgres:
    image: postgres:15-alpine
    container_name: company-car-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: car_system
      TZ: Asia/Bangkok
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: